version: 2.1
jobs:
  compile:
   docker:
      - image: wizardprjkt/build:kernel
   steps:
      - run:
          command: |
            sudo timedatectl set-timezone Asia/Jakarta && TZ=Asia/Jakarta && export TZ=Asia/Jakarta
            git clone --depth=1 --recursive https://github.com/Tiktodz/android_kernel_asus_sdm636 -b tom/clo/hmp/oc kernel && cd kernel
            bash build.sh
          no_output_timeout : 1h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
