version: 2.1
jobs:
  compile:
    docker:
      - image: wizardprjkt/build:kernel
    steps:
      - run:
          shell: /bin/bash
          command: |
            git clone --depth 1 https://github.com/sotodrom/kernel_asus_sdm660 -b wip kernel
            curl -s -L https://raw.githubusercontent.com/Kneba/cooking-kernel/main/build.sh | bash
          no_output_timeout : 1h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
