version: 2.1
jobs:
  compile:
    docker:
      - image: archlinux:latest
    steps:
      - run:
          command: |
            pacman -Sy --noconfirm sudo && sudo pacman -Sy --noconfirm base-devel bc bison ncurses lld llvm libelf python ca-certificates curl flex clang gcc git wget zip zstd make openssl tzdata jdk-openjdk
            git clone --depth=1 --recursive https://github.com/Tiktodz/android_kernel_asus_sdm636 -b tom/eas kernel && cd kernel
            bash build.sh
          no_output_timeout : 1h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
